mc: False
is_h4l: False
input_files:
  [
    "/data3/fmazzasc/hyp_run_3/pp2023/skimmed/AO2D.root",
  ]
output_dir: "../results/"
output_file: "HypertritonResults_skimmed"
selection:
  {
    # "fEtaHe3" : "abs(fEtaHe3) < 0.9",
    # "fEtaPi" : "abs(fEtaPi) <   0.9",
    # "fNTPCclusHe": "fNTPCclusHe > 100",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -1",
      "fTPCsignalPi": "fTPCsignalPi < 1000.",
      "fTPCmomHe": "fTPCmomHe > 0.5",
      "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",

  }
is_matter: "antimatter"
calibrate_he_momentum: False
skip_out_tree: False