mc: True
is_h4l: False
# input_files: ["/data/shared/hyp_run_3/mc/anchoring_2022_apass4/AO2D_h3l_mc.root"]
input_files: ["/home/fmazzasc/AO2D.root"]
output_dir: "../results/"
output_file: "HypertritonResults_non_surv"
selection:
  {
    "fIsSurvEvSel" : "fIsSurvEvSel==False"
  }

is_matter: "both"
calibrate_he_momentum: True
skip_out_tree: False