mc: False
is_h4l: False
input_files:
  [
    "/data3/fmazzasc/hyp_run_3/pp2022/LHC22_highIR/AO2D.root",
  ]
output_dir: "../results/"
output_file: "HypertritonResults_antimatter"
selection:
  {
    "fEtaHe3" : "abs(fEtaHe3) < 0.9",
    "fEtaPi" : "abs(fEtaPi) < 0.9",
    "fNTPCclusPi": "fNTPCclusPi > 70",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -3.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
  }
is_matter: "antimatter"
calibrate_he_momentum: True
skip_out_tree: False